info:
  app:
    name: catalog-typeahead-service
    description: Gives search suggestions based on other searches

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8080

spring:  

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
    profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/