info:
  app:
    name: catalog-typeahead-service
    description: Gives search suggestions based on other searches

server:
  port: 0

elastic:
  hosts:
    - localhost
  suggestionIndex: suggestioncounters
  expressionIndex: expressionrecords